name: Go

on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.19', '1.20','1.21']
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go }}
      steps:  
        - uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}
  
        - name: Go Build
          run: |
            go build cmd/dfence.go

        - name: Go Tests
          run: |
            go test ./...       


