# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go:
          - "1.18"
          - "1.19"
          - "1.20"          
          - "1.21"
      fail-fast: false    
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go }}      
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go mod tidy; go build -v ./...

    - name: Test
      run: go test -v ./...
